### ISSUE TITLE
type information in the response body is missing the schema reference

### ISSUE THREAD

**Issue by ulaBLUE** [wdullaer/raml2html-slate-theme#27] opened 2017-10-09 13:23 UTC
Hi,
Thanks for the theme. It is really good to see other layouts.
I have some RAML response body like below and I cannot see the type (schema) reference in RAML is shown in the final HTML. is it possible to do so ? 

The type is defined at the beginning of the RAML using `types:`. I tried to play with but can only output the word "xml". How can we show "type" as like "orders" and may be provide a link to type schema defined in the beginning. 

```
    responses:
      200:
      .....
        body:
          application/xml:
            description: XML representation of the list of orders
            type: order
            example: !include examples/order.xml

```

**Comment by wdullaer** [comment] 2017-10-12 10:35
By default the theme will only render examples for a json payload.
You will need to pass a commandline option to have it render xml (or multiple body types)

```bash
raml2html \
--theme 'raml2html-slate-theme' \
-o 'path/to/output/file.html' \
--language-tabs "['xml']"
-i 'path/to/raml/file.raml'
```

See language tabs here: https://github.com/wdullaer/raml2html-slate-theme#options

**Comment by ulaBLUE** [comment] 2017-10-12 13:03
sorry may be I am not clear. 

It is showing me the examples of both XML and JSON (by default) but the type (for example 'order') is not displayed. 

After adding the languages-tab, it did not even show the examples. And the type information is like before shown as "object". Please find attached image.

![res](https://user-images.githubusercontent.com/16258310/31497166-74742fdc-af5e-11e7-9319-4269d36fe93e.png)

**Comment by wdullaer** [comment] 2017-10-12 15:21
The type should show the string `orders` in this case.
It won't create a hyperlink (for now).
In case your type is defined inline, it'll show the entire type definition.

Can you post a minimal RAML file that reproduces this, so I can easily debug it (and potentially add it to my test fixtures)?

**Comment by yyamano** [comment] 2019-08-05 00:42
@wdullaer I can't reproduce the problem and there was no feedback for more than 20 months. We can close it.

**Closed** 2019-08-15 12:20 UTC
